import pandas as pd
import plotly as pl
import plotly_express as px

# Read the csv file with pandas or polars:
df = pd.read_csv(r'C:\Users\diego\Desktop\licitaciones\licitaciones.csv')
print(df.head(5))

# EDIT and FILTER the country_subentities columns:
subentity_rename = {
    'COMUNIDAD DE MADRID': 'Madrid',
    'Comunidad de Madrid': 'Madrid',
    'Gipuzkoa': 'Gipúzcoa',
    'Tenerife': 'Santa Cruz De Tenerife',
    'La Gomera': 'Santa Cruz De Tenerife',
    'El Hierro': 'Santa Cruz De Tenerife',
    'La Palma': 'Santa Cruz De Tenerife',
    'Alicante (Alacant)': 'Alacant/Alicante',
    'Alicante / Alacant': 'Alacant/Alicante',
    'Valencia/València': 'Valencia',
    'Gran Canaria': 'Las Palmas',
    'Fuerteventura': 'Las Palmas',
    'Bizkaia': 'Bizkaia/Vizcaya',
    'Principado de Asturias': 'Asturias',
    'Región de Murcia': 'Murcia',
}

city_to_subentity = {
    'Mérida': 'Badajoz',
    'Madrid': 'Madrid',
    'Valencia': 'València/Valencia',
    'Aljaraque': 'Huelva',
    'la laguna': 'Santa Cruz De Tenerife',
    'Burgos': 'Burgos',
    'Alicante': 'Alacant/Alicante',
    'OVIEDO': 'Asturias',
    'Sevilla': 'Sevilla',
    'Gijón': 'Cantabria',
    'Barcelona': 'Barcelona',
    'Pontevedra': 'Pontevedra',
    'Cartagena': 'Murcia',
    'Santa Cruz de Tenerife': 'Santa Cruz De Tenerife',
    'San Cristóbal de La Laguna -Santa Cruz de Tenerife': 'Santa Cruz De Tenerife',
    'Vigo': 'Pontevedra',
    'Santa Lucía de Tirajana (Gran Canaria)': 'Las Palmas',
    'Campo de Criptana ': 'Ciudad Real',
    'Zamora': 'Zamora',
    'Zaragoza': 'Zaragoza',
    'Badajoz': 'Badajoz',
    'Valladolid': 'Valladolid',
    'Teguise (Lanzarote)': 'Las Palmas',
    'Lugo': 'Lugo',
    'Reus': 'Tarragona',
    'Arrecife': 'Las Palmas',
    'A Coruña': 'A Coruña',
    'San Vicente del Raspeig': 'València/Valencia',
    'Villagonzalo de Tormes': 'Salamanca',
    'Mansilla de las Mulas (León)': 'León',
    'Elche': 'Alacant/Alicante',
    'Alberite': 'La Rioja',
    'Majadahonda (Madrid)': 'Madrid',
    'Santurtzi': 'Bizkaia/Vizcaya',
    'Castellón': 'Castelló/Castellón',
    'Siero': 'Asturias',
    'Granollers': 'Barcelona',
    'Las Palmas de Gran Canaria': 'Las Palmas',
    'Langreo': 'Asturias',
    'Rubayo, Cantabria': 'Cantabria',
    'Toledo': 'Toledo',
    'Vinarós': 'Castelló/Castellón',
    'Pasaia': 'Gipuzkoa/Guipúzcoa',
    'Oleiros': 'A Coruña',
    'Albacete': 'Albacete',
    'Palma de Mallorca': 'Illes Balears',
    'El Higuerón-Córdoba': 'Córdoba',
    'El Pardo (Madrid)': 'Madrid',
    'Bilbao': 'Bizkaia/Vizcaya',
    'Cartagena  (Murcia)': 'Murcia',
    'Pozuelo de Alarcón': 'Madrid',
    'Torrelavega': 'Cantabria',
    'Cubillos del Sil (León)': 'León',
    'Torrejón de Ardoz, Madrid': 'Madrid',
    'Logroño': 'La Rioja',
    'Lardero, La Rioja': 'La Rioja',
    'San Fernando': 'Cádiz',
    'Molina del Segura (Murcia)': 'Murcia',
    'Ferrol (Coruña)': 'A Coruña',
    'Guadalajara': 'Guadalajara',
    'Oviedo': 'Asturias',
    'Gijón ': 'Cantabria',
    'Zamudio. (Bizkaia)': 'Bizkaia/Vizcaya',
    'Muriedas - Camargo': 'Cantabria',
    'Culleredo': 'A Coruña',
    'Murcia': 'Murcia',
    'Almería': 'Almería',
    'León': 'León',
    'Algete': 'Madrid',
    'San Sebastián de la Gomera': 'Santa Cruz De Tenerife',
    'Tarragona': 'Tarragona',
    'MALAGA': 'Málaga',
    'Ampuero': 'Cantabria',
    'Aljaraque (Huelva)': 'Huelva',
    'El Escorial (Madrid)': 'Madrid',
    'Torrejón de Ardoz': 'Madrid',
    'Cuenca': 'Cuenca',
    'Girona': 'Girona',
    'ÁVILA': 'Ávila',
    'Melilla': 'Melilla',
    'Teruel': 'Teruel',
    'Rota (Cádiz)': 'Cádiz',
    'Huelva': 'Huelva',
    'San Vicente Raspeig (Alicante)': 'Alacant/Alicante',
    'Córdoba': 'Córdoba',
    'Posada de Llanera': 'Asturias',
    'Plasencia': 'Cáceres',
    'Cartagena': 'Murcia',
    'Medina del Campo ': 'Valladolid',
    'Calp (Alicante)': 'Alacant/Alicante',
    'Madrid ': 'Madrid',
    'Los Barrios': 'Cádiz',
    'Puerto del Rosario': 'Las Palmas',
    'la laguna': 'Santa Cruz De Tenerife',
    'Gijón (Asturias)': 'Asturias',
    'MADRID': 'Madrid',
    'Soria': 'Soria',
    'Sant Cugat del Vallès': 'Barcelona',
    'Santander': 'Cantabria',
    'Medina del Campo': 'Valladolid',
    'Navarrete (La Rioja)': 'La Rioja',
    'San Lorenzo de El Escorial': 'Madri',
    'Santa Eulária des Riu (Balears)': 'Illes Balears',
    'Mieres': 'Asturias',
    'Bergondo': 'A Coruña',
    'CASTELLON': 'Castelló/Castellón',
    'Jaén': 'Jaén',
    'Pamplona': 'Navarra',
    'Cádiz': 'Cádiz',
    'Cabañaquinta': 'Asturias',
    'VALENCIA': 'València/Valencia',
    'Salamanca': 'Salamanca',
    'Barakaldo': 'Bizkaia/Vizcaya',
    'Mazarrón (Murcia)': 'Murcia',
    'Cangas de Onís, Principado de Asturias': 'Asturias',
    'Cuéllar': 'Segovia',
    'San Martín de la Vega (Madrid)': 'Madrid',
    'Mislata': 'València/Valencia',
    'Huesca': 'Huesca',
    'Pájara (Fuerteventura)': 'Las Palmas',
    'Getafe': 'Madrid',
    'VIGO': 'Pontevedra',
    'Aranda de Duero (Burgos)': 'Burgos',
    'Jaca (Huesca)': 'Huesca',
    'Mislata (Valencia)': 'València/Valencia',
    'Cubas de la Sagra (Madrid)': 'Madrid',
    'Ourense': 'Ourense',
    'San Agustín del Guadalix': 'Madrid',
    'Vilagarcia de Arousa': 'Pontevedra',
    'Talavera de la Reina (Toledo)': 'Toledo',
    'Pozoblanco (Córdoba)': 'Córdoba',
    'HUESCA': 'Huesca',
    'Buniel (Burgos)': 'Burgos',
    'Palma Mallorca': 'Illes Balears',
    'Las Palmas': 'Las Palmas',
    'Amorebieta-Etxano': 'Bizkaia/Vizcaya',
    'Ceuta': 'Ceuta',
    'Zamudio (Vizcaya)': 'Bizkaia/Vizcaya',
    'Armilla ': 'Granada',
    'LUGO': 'Lugo',
    'Villabona Llanera': 'Asturias',
    'Colindres (Cantabria)': 'Cantabria',
    'Los Realejos': 'Santa Cruz De Tenerife',
    'Estremera (Madrid)': 'Madrid',
    'Granada': 'Granada',
    'Llanes': 'Asturias',
    'Vitoria': 'Araba/Álava',
    'CADIZ': 'Cádiz',
    'Cartagena (Murcia)': 'Murcia',
}

df['subentity'] = df['country subentity'].replace(subentity_rename)
df['subentity'] = df['city'].replace(city_to_subentity)

df = df[
    ~df['subentity'].isin(
        [
            'ESPAÑA',
            'CANARIAS',
            'NORESTE',
            'No country subentity available',
            'CENTRO (ES)',
            'ES',
            'Castilla y León',
            'Castilla-La Mancha',
            'País Vasco',
            'Andalucía',
            'Cataluña',
            'Comunidad Valenciana',
            'Aragón',
            'FRANCE',
        ]
    )
]


amount_subentity_chart = (
    df.groupby('subentity')['total amount'].sum().reset_index().sort_values(by='total amount', ascending=True)
)
fig = px.bar(
    amount_subentity_chart,
    x='subentity',
    y='total amount',
    text='total amount',
    title='Total amount by subentity',
    color='total amount',
)
fig.update_traces(texttemplate='%{text:.2s}', textposition='outside')
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
fig.show()
